services:
  bentopdf:
    # GitHub Container Registry (Recommended)
    # simple mode - ghcr.io/alam00000/bentopdf-simple:latest
    # default mode - ghcr.io/alam00000/bentopdf:latest
    # Docker Hub (Alternative)
    # simple mode - bentopdfteam/bentopdf-simple:latest
    # default mode - bentopdfteam/bentopdf:latest
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
